version: "3"

services:
  app:
    build:
      context: .
    container_name: app
    tty: true
    ports:
      - "3000:3000"
    networks:
      - appnet
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      seq:
        condition: service_started
    environment:
      - SEQ_URL=http://seq # Defina a URL do Seq como uma variável de ambiente
  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_ADMIN_PASSWORD=admin
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  node_modules:
